// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "labactivectrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CLabactivectrl1

IMPLEMENT_DYNCREATE(CLabactivectrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLabactivectrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CLabactivectrl1 operations
